import mongoose from 'mongoose'
import dotenv from 'dotenv'
import users from './data/Users.js'
import products from './data/products.js'
import User from './models/userModel.js'
import Product from './models/productModel.js'
import Order from './models/orderModel.js'